services:
  app:
    build: .
    container_name: tc_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - db

  vite:
    image: node:20
    working_dir: /var/www/html
    container_name: tc_vite
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: mysql:8
    container_name: tc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tc
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  vendor:
  node_modules:
